- name: "{{ os }} - Send Mail if host backup failed"
  mail:
    host: "{{ mail_host}}"
    port: "{{ mail_port }}"
    sender: "{{ mail_sender }}"
    username: "{{ mail_username }}"
    password: "{{ mail_password }}"
    to: "{{ mail_to }}"
    subject: Configuration backup failed on host "{{ inventory_hostname }}"
  delegate_to: localhost
  when: step == "fail"

- name: Mail Message - Network configuration backup finished
  mail:
    host: "{{ mail_host}}"
    port: "{{ mail_port }}"
    sender: "{{ mail_sender }}"
    username: "{{ mail_username }}"
    password: "{{ mail_password }}"
    to: "{{ mail_to }}"
    subject: Network configuration backup finished
  delegate_to: localhost
  when: step == "finished"