- name: Arista - show running-config
  eos_command:
    commands: 'show running-config'
  register: output
  ignore_errors: yes

- name: Arista - Save the output
  vars:
    clean_config: "{{ output.stdout[0]|clean_config(clean_patterns) }}"
  local_action: copy content={{clean_config}} dest={{backup_dir}}/{{file_name}}

- name: Arista - Process the file
  command:
    argv:
      - python3
      - scripts/netconf-backup.py
      - "{{ inventory_hostname }}"
      - "{{ file_name }}"
      - "{{ backup_dir }}"
      - "{{ keep_local_history }}"
      - "{{ historic_files_to_keep }}"
  delegate_to: localhost
  when: output.failed == false
